export const compliments = [
  "Hey {name}, your code is cleaner than a freshly linted repo.",
  "Wow {name}, you explain things better than most documentation.",
  "{name}, you commit early and often. Respect.",
  "{name}, your variable names actually make sense.",
  "Hey {name}, you debug like a senior developer.",
  "{name}, your pull requests are a joy to review.",
  "Not gonna lie {name}, your code comments are actually helpful.",
  "{name}, you handle merge conflicts like a pro.",
  "Hey {name}, even your error messages are user-friendly.",
  "{name}, your indentation is *chef's kiss*.",
  "{name}, you ask the best questions in class.",
  "Hey {name}, your README is better than most company docs.",
  "{name}, you break down problems like a true engineer.",
  "{name}, your Git history tells a beautiful story.",
  "Hey {name}, you refactor code like Marie Kondo organizes closets.",
  "{name}, your API responses are cleaner than a 200 OK.",
  "{name}, you write tests before anyone has to ask. Legend.",
  "Hey {name}, even your console.logs are well-formatted.",
  "{name}, your folder structure makes senior devs jealous.",
  "{name}, you actually read the error message before panicking. Rare skill.",
  "Hey {name}, your code reviews are constructive and kind.",
  "{name}, you Google things efficiently. That IS a skill.",
  "{name}, your functions do one thing and do it well. Beautiful.",
  "Hey {name}, you are the teammate everyone wants in a group project.",
  "{name}, your loops never run forever. Impressive.",
  "{name}, your JSON is always valid on the first try.",
  "Hey {name}, you understand scope better than most developers.",
  "{name}, your async/await game is strong.",
  "{name}, you never push directly to main. We respect that.",
  "Hey {name}, your terminal history is a masterclass in CLI usage.",
  "{name}, you make even callback hell look manageable.",
  "Hey {name}, your .gitignore is perfectly curated.",
  "{name}, you never forget a semicolon. Or do you? Either way, it works.",
  "{name}, your package.json has zero unnecessary dependencies.",
  "Hey {name}, your fetch requests always handle errors. Always.",
  "{name}, your CSS could never be called a code smell.",
  "{name}, you understand the event loop better than most interviewers.",
  "Hey {name}, your branches are named so well they're basically documentation.",
  "{name}, you close every resource you open. Even the fridge.",
  "{name}, your .env file is never committed. Security legend.",
  "Hey {name}, your for loops always terminate. That's more rare than you think.",
  "{name}, you understand the difference between == and ===. Respect.",
  "{name}, your try-catch blocks actually catch the right errors.",
  "Hey {name}, you read the stack trace top to bottom like a detective.",
  "{name}, your terminal prompt is probably customized. Power user energy.",
  "{name}, you name your variables like poetry. Readable poetry.",
  "Hey {name}, your arrays are never mutated by accident.",
  "{name}, you know when to use map and when to use forEach. That's wisdom.",
  "{name}, your objects are always properly destructured.",
  "Hey {name}, your promises never go unhandled.",
  "{name}, you actually understand what npm install does. Most people don't.",
  "{name}, your arrow functions are concise and confident.",
  "Hey {name}, your imports are always at the top of the file. Order matters.",
  "{name}, you never nest more than three levels deep. Your future self thanks you.",
  "{name}, you delete dead code instead of commenting it out. Brave.",
  "Hey {name}, your HTTP status codes are always correct. Even the 418s.",
  "{name}, your server starts on the first try. Every time.",
  "{name}, you log useful messages, not just 'here' and 'test123'.",
  "Hey {name}, your Express routes are RESTful and beautiful.",
  "{name}, your merge commits tell a story of collaboration.",
  "{name}, you push small commits, not one giant blob. Chef's kiss.",
  "Hey {name}, you use template literals instead of string concatenation. Modern.",
  "{name}, your code works on your machine AND everyone else's.",
  "{name}, you read the docs before asking. Then you ask great questions anyway.",
  "Hey {name}, your PRs have descriptions. Actual descriptions. With context.",
  "{name}, your functions never exceed 20 lines. Discipline.",
  "{name}, you understand null vs undefined. That alone puts you ahead.",
  "Hey {name}, your switch cases always have a default. Safety first.",
  "{name}, your API returns proper error messages, not just 'something went wrong'.",
  "{name}, you test edge cases that nobody else thinks of.",
  "Hey {name}, your JSON is always properly nested. Not a dangling comma in sight.",
  "{name}, you know that 'it works' is not the same as 'it's done'. Quality mindset.",
  "{name}, you ask 'why' before 'how'. That's engineering thinking.",
  "Hey {name}, your Docker containers start without errors. First try.",
  "{name}, your YAML indentation is always correct. You might be a wizard.",
  "{name}, you use const by default and let only when needed. Disciplined.",
  "Hey {name}, your callbacks are never more than two levels deep.",
  "{name}, your code passes the linter with zero warnings.",
  "{name}, your file names are descriptive and consistent. Underrated skill.",
  "Hey {name}, you actually use the debugger instead of 100 console.logs.",
  "{name}, your database queries are efficient and readable.",
  "{name}, you handle the sad path, not just the happy path.",
  "Hey {name}, your curl commands work on the first try.",
  "{name}, you know the difference between authentication and authorization.",
  "{name}, your server never crashes silently. It exits with grace.",
  "Hey {name}, you write code that your future teammates will thank you for.",
  "{name}, your comments explain why, not what. That's the difference.",
  "{name}, your npm scripts are organized like a Swiss train schedule.",
  "Hey {name}, you close your HTML tags and your database connections.",
  "{name}, you can explain recursion without using the word recursion.",
  "{name}, your README has installation steps that actually work.",
  "Hey {name}, you respond to code review feedback with grace and speed.",
  "{name}, you never hardcode values that should be environment variables.",
  "{name}, your SQL queries use parameterized inputs. Bobby Tables approves.",
  "Hey {name}, you understand REST so well you could explain it to your grandma.",
  "{name}, your git log is cleaner than most people's desks.",
  "{name}, you know that a 204 means success, not failure. Not everyone does.",
  "Hey {name}, your middleware is in the right order. Always.",
  "{name}, you deploy on Mondays with confidence. Fearless.",
  "Hey {name}, you are proof that great developers are made, not born.",
];
