CREATE TABLE IF NOT EXISTS products (
    id        SERIAL          PRIMARY KEY,
    title     TEXT            NOT NULL,
    price     NUMERIC(10, 2)  NOT NULL,
    category  TEXT            NOT NULL,
    image_url TEXT            NULL,
    details   JSONB           NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_details ON products USING GIN (details);


INSERT INTO products (title, price, category, details) VALUES
('Black runner EU38', 107.91, 'sneakers', '{"size_eu": 38, "size_us": 5.5, "width": "wide", "color": "black"}'::jsonb),
('Floral midi work dress', 53.21, 'dress', '{"size": "L", "length": "midi", "occasion": "work", "color": "floral"}'::jsonb),
('Tan suede belt', 45.93, 'belt', '{"length_cm": 120, "material": "suede", "buckle": "automatic", "color": "tan"}'::jsonb),
('Black runner EU44', 98.55, 'sneakers', '{"size_eu": 44, "size_us": 10, "width": "narrow", "color": "black"}'::jsonb),
('Red knee formal dress', 56.33, 'dress', '{"size": "S", "length": "knee", "occasion": "work", "color": "red"}'::jsonb),
('Black runner EU41', 69.01, 'sneakers', '{"size_eu": 41, "size_us": 8, "width": "regular", "color": "black"}'::jsonb),
('Grey slim tee', 24.31, 'tshirt', '{"color": "grey", "size": "XXL", "material": "cotton-blend", "fit": "relaxed"}'::jsonb),
('Black midi casual dress', 45.29, 'dress', '{"size": "L", "length": "midi", "occasion": "formal", "color": "black"}'::jsonb),
('Cognac faux-leather belt', 40.23, 'belt', '{"length_cm": 90, "material": "faux-leather", "buckle": "pin", "color": "cognac"}'::jsonb),
('Forest Green oversized tee', 13.24, 'tshirt', '{"color": "forest green", "size": "M", "material": "organic cotton", "fit": "oversized"}'::jsonb),
('Raw Denim slim jeans W34', 46.68, 'jeans', '{"waist": 34, "inseam": 36, "color": "raw denim", "stretch": true}'::jsonb),
('White relaxed tee', 17.9, 'tshirt', '{"color": "white", "size": "XXL", "material": "linen", "fit": "slim"}'::jsonb),
('Brown suede belt', 26.89, 'belt', '{"length_cm": 90, "material": "suede", "buckle": "reversible", "color": "brown"}'::jsonb),
('Sky Blue oversized tee', 18.01, 'tshirt', '{"color": "sky blue", "size": "XS", "material": "organic cotton", "fit": "oversized"}'::jsonb),
('Black slim jeans W28', 54.44, 'jeans', '{"waist": 28, "inseam": 30, "color": "black", "stretch": true}'::jsonb),
('Black runner EU39', 109.49, 'sneakers', '{"size_eu": 39, "size_us": 6.5, "width": "wide", "color": "black"}'::jsonb),
('Red regular tee', 17.17, 'tshirt', '{"color": "red", "size": "M", "material": "cotton-blend", "fit": "oversized"}'::jsonb),
('Navy knee party dress', 109.64, 'dress', '{"size": "XL", "length": "knee", "occasion": "formal", "color": "navy"}'::jsonb),
('Forest Green regular tee', 22.17, 'tshirt', '{"color": "forest green", "size": "S", "material": "cotton-blend", "fit": "slim"}'::jsonb),
('Floral maxi party dress', 120.22, 'dress', '{"size": "L", "length": "maxi", "occasion": "party", "color": "floral"}'::jsonb),
('Grey slim jeans W34', 66.28, 'jeans', '{"waist": 34, "inseam": 36, "color": "grey", "stretch": true}'::jsonb),
('Black oversized tee', 13.1, 'tshirt', '{"color": "black", "size": "M", "material": "cotton", "fit": "regular"}'::jsonb),
('Black runner EU39', 94.3, 'sneakers', '{"size_eu": 39, "size_us": 6.5, "width": "wide", "color": "black"}'::jsonb),
('White relaxed tee', 21.78, 'tshirt', '{"color": "white", "size": "XS", "material": "organic cotton", "fit": "relaxed"}'::jsonb),
('White relaxed tee', 17.58, 'tshirt', '{"color": "white", "size": "XXL", "material": "cotton-blend", "fit": "slim"}'::jsonb),
('Raw Denim slim jeans W31', 87.51, 'jeans', '{"waist": 31, "inseam": 36, "color": "raw denim", "stretch": true}'::jsonb),
('Brown suede belt', 31.62, 'belt', '{"length_cm": 95, "material": "suede", "buckle": "automatic", "color": "brown"}'::jsonb),
('Brown faux-leather belt', 42.94, 'belt', '{"length_cm": 110, "material": "faux-leather", "buckle": "pin", "color": "brown"}'::jsonb),
('Black slim jeans W38', 88.44, 'jeans', '{"waist": 38, "inseam": 32, "color": "black", "stretch": true}'::jsonb),
('Black runner EU38', 111.93, 'sneakers', '{"size_eu": 38, "size_us": 5.5, "width": "regular", "color": "black"}'::jsonb),
('Forest Green relaxed tee', 27.95, 'tshirt', '{"color": "forest green", "size": "L", "material": "polyester", "fit": "slim"}'::jsonb),
('Tan suede belt', 43.66, 'belt', '{"length_cm": 100, "material": "suede", "buckle": "pin", "color": "tan"}'::jsonb),
('Raw Denim slim jeans W28', 80.39, 'jeans', '{"waist": 28, "inseam": 30, "color": "raw denim", "stretch": true}'::jsonb),
('Brown canvas belt', 24.44, 'belt', '{"length_cm": 95, "material": "canvas", "buckle": "reversible", "color": "brown"}'::jsonb),
('Black canvas belt', 22.15, 'belt', '{"length_cm": 115, "material": "canvas", "buckle": "pin", "color": "black"}'::jsonb),
('Red knee casual dress', 78.35, 'dress', '{"size": "L", "length": "knee", "occasion": "formal", "color": "red"}'::jsonb),
('Washed Blue slim jeans W30', 92.22, 'jeans', '{"waist": 30, "inseam": 34, "color": "washed blue", "stretch": true}'::jsonb),
('Grey slim jeans W36', 75.74, 'jeans', '{"waist": 36, "inseam": 36, "color": "grey", "stretch": false}'::jsonb),
('Black leather belt', 52.55, 'belt', '{"length_cm": 110, "material": "leather", "buckle": "reversible", "color": "black"}'::jsonb),
('White regular tee', 23.52, 'tshirt', '{"color": "white", "size": "XL", "material": "cotton", "fit": "relaxed"}'::jsonb),
('White runner EU38', 115.2, 'sneakers', '{"size_eu": 38, "size_us": 5.5, "width": "wide", "color": "white"}'::jsonb),
('Brown canvas belt', 50.1, 'belt', '{"length_cm": 120, "material": "canvas", "buckle": "automatic", "color": "brown"}'::jsonb),
('Burgundy knee casual dress', 61.95, 'dress', '{"size": "XL", "length": "knee", "occasion": "formal", "color": "burgundy"}'::jsonb),
('White runner EU39', 142.63, 'sneakers', '{"size_eu": 39, "size_us": 6.5, "width": "narrow", "color": "white"}'::jsonb),
('Floral knee work dress', 111.38, 'dress', '{"size": "XL", "length": "knee", "occasion": "party", "color": "floral"}'::jsonb),
('Forest Green oversized tee', 26.85, 'tshirt', '{"color": "forest green", "size": "XS", "material": "organic cotton", "fit": "regular"}'::jsonb),
('Indigo slim jeans W36', 61.25, 'jeans', '{"waist": 36, "inseam": 36, "color": "indigo", "stretch": false}'::jsonb),
('Blue runner EU45', 65.47, 'sneakers', '{"size_eu": 45, "size_us": 11, "width": "regular", "color": "blue"}'::jsonb),
('Tan leather belt', 45.04, 'belt', '{"length_cm": 110, "material": "leather", "buckle": "automatic", "color": "tan"}'::jsonb),
('Grey runner EU38', 66.45, 'sneakers', '{"size_eu": 38, "size_us": 5.5, "width": "narrow", "color": "grey"}'::jsonb),
('Floral knee formal dress', 39.21, 'dress', '{"size": "L", "length": "knee", "occasion": "casual", "color": "floral"}'::jsonb),
('Red mini work dress', 128.46, 'dress', '{"size": "XL", "length": "mini", "occasion": "casual", "color": "red"}'::jsonb),
('Off-White runner EU46', 81.63, 'sneakers', '{"size_eu": 46, "size_us": 12, "width": "regular", "color": "off-white"}'::jsonb),
('Black canvas belt', 35.57, 'belt', '{"length_cm": 120, "material": "canvas", "buckle": "pin", "color": "black"}'::jsonb),
('Black suede belt', 53.9, 'belt', '{"length_cm": 120, "material": "suede", "buckle": "pin", "color": "black"}'::jsonb),
('Washed Blue slim jeans W28', 80.81, 'jeans', '{"waist": 28, "inseam": 30, "color": "washed blue", "stretch": false}'::jsonb),
('Forest Green regular tee', 10.49, 'tshirt', '{"color": "forest green", "size": "M", "material": "organic cotton", "fit": "slim"}'::jsonb),
('Emerald knee formal dress', 75.96, 'dress', '{"size": "M", "length": "knee", "occasion": "formal", "color": "emerald"}'::jsonb),
('Grey slim jeans W28', 97.22, 'jeans', '{"waist": 28, "inseam": 34, "color": "grey", "stretch": true}'::jsonb),
('Burgundy mini formal dress', 83.17, 'dress', '{"size": "L", "length": "mini", "occasion": "formal", "color": "burgundy"}'::jsonb),
('Grey runner EU42', 142.64, 'sneakers', '{"size_eu": 42, "size_us": 8.5, "width": "regular", "color": "grey"}'::jsonb),
('Emerald midi party dress', 87.04, 'dress', '{"size": "XS", "length": "midi", "occasion": "formal", "color": "emerald"}'::jsonb),
('Black runner EU38', 146.07, 'sneakers', '{"size_eu": 38, "size_us": 5.5, "width": "narrow", "color": "black"}'::jsonb),
('Navy regular tee', 11.86, 'tshirt', '{"color": "navy", "size": "S", "material": "cotton-blend", "fit": "regular"}'::jsonb),
('Cognac leather belt', 23.06, 'belt', '{"length_cm": 100, "material": "leather", "buckle": "automatic", "color": "cognac"}'::jsonb),
('Cognac canvas belt', 55.73, 'belt', '{"length_cm": 120, "material": "canvas", "buckle": "pin", "color": "cognac"}'::jsonb),
('Black slim jeans W34', 85.74, 'jeans', '{"waist": 34, "inseam": 30, "color": "black", "stretch": false}'::jsonb),
('Sky Blue regular tee', 24.58, 'tshirt', '{"color": "sky blue", "size": "XL", "material": "cotton", "fit": "relaxed"}'::jsonb),
('Black faux-leather belt', 20.73, 'belt', '{"length_cm": 100, "material": "faux-leather", "buckle": "automatic", "color": "black"}'::jsonb),
('Black runner EU43', 73.86, 'sneakers', '{"size_eu": 43, "size_us": 9.5, "width": "regular", "color": "black"}'::jsonb),
('Navy maxi formal dress', 124.22, 'dress', '{"size": "XS", "length": "maxi", "occasion": "formal", "color": "navy"}'::jsonb),
('Burgundy midi party dress', 92.58, 'dress', '{"size": "XL", "length": "midi", "occasion": "casual", "color": "burgundy"}'::jsonb),
('White runner EU43', 55.71, 'sneakers', '{"size_eu": 43, "size_us": 9.5, "width": "wide", "color": "white"}'::jsonb),
('Grey runner EU46', 141.93, 'sneakers', '{"size_eu": 46, "size_us": 12, "width": "wide", "color": "grey"}'::jsonb),
('Navy oversized tee', 26.58, 'tshirt', '{"color": "navy", "size": "XL", "material": "polyester", "fit": "slim"}'::jsonb),
('Grey slim jeans W28', 46.7, 'jeans', '{"waist": 28, "inseam": 34, "color": "grey", "stretch": false}'::jsonb),
('Cognac leather belt', 53.63, 'belt', '{"length_cm": 95, "material": "leather", "buckle": "pin", "color": "cognac"}'::jsonb),
('Red runner EU44', 119.65, 'sneakers', '{"size_eu": 44, "size_us": 10, "width": "wide", "color": "red"}'::jsonb),
('Raw Denim slim jeans W38', 88.95, 'jeans', '{"waist": 38, "inseam": 32, "color": "raw denim", "stretch": true}'::jsonb),
('White relaxed tee', 11.81, 'tshirt', '{"color": "white", "size": "XS", "material": "cotton", "fit": "slim"}'::jsonb),
('Black slim tee', 14.92, 'tshirt', '{"color": "black", "size": "XL", "material": "cotton-blend", "fit": "oversized"}'::jsonb),
('Sky Blue slim tee', 27.32, 'tshirt', '{"color": "sky blue", "size": "L", "material": "polyester", "fit": "relaxed"}'::jsonb),
('Brown faux-leather belt', 52.31, 'belt', '{"length_cm": 90, "material": "faux-leather", "buckle": "pin", "color": "brown"}'::jsonb),
('Grey runner EU43', 130.05, 'sneakers', '{"size_eu": 43, "size_us": 9.5, "width": "narrow", "color": "grey"}'::jsonb),
('Black runner EU44', 68.34, 'sneakers', '{"size_eu": 44, "size_us": 10, "width": "regular", "color": "black"}'::jsonb),
('Washed Blue slim jeans W32', 40.42, 'jeans', '{"waist": 32, "inseam": 30, "color": "washed blue", "stretch": true}'::jsonb),
('Floral maxi party dress', 99.17, 'dress', '{"size": "XL", "length": "maxi", "occasion": "party", "color": "floral"}'::jsonb),
('Light Blue slim jeans W38', 52.84, 'jeans', '{"waist": 38, "inseam": 32, "color": "light blue", "stretch": false}'::jsonb),
('Forest Green regular tee', 10.91, 'tshirt', '{"color": "forest green", "size": "S", "material": "polyester", "fit": "regular"}'::jsonb),
('Black runner EU44', 61.98, 'sneakers', '{"size_eu": 44, "size_us": 10, "width": "wide", "color": "black"}'::jsonb),
('Floral maxi work dress', 103.23, 'dress', '{"size": "L", "length": "maxi", "occasion": "party", "color": "floral"}'::jsonb),
('Raw Denim slim jeans W38', 96.8, 'jeans', '{"waist": 38, "inseam": 32, "color": "raw denim", "stretch": false}'::jsonb),
('Floral midi formal dress', 112.94, 'dress', '{"size": "S", "length": "midi", "occasion": "work", "color": "floral"}'::jsonb),
('Brown suede belt', 37.75, 'belt', '{"length_cm": 95, "material": "suede", "buckle": "automatic", "color": "brown"}'::jsonb),
('Black canvas belt', 27.67, 'belt', '{"length_cm": 95, "material": "canvas", "buckle": "reversible", "color": "black"}'::jsonb),
('Indigo slim jeans W28', 91.57, 'jeans', '{"waist": 28, "inseam": 30, "color": "indigo", "stretch": true}'::jsonb),
('Red knee party dress', 66.17, 'dress', '{"size": "XS", "length": "knee", "occasion": "formal", "color": "red"}'::jsonb),
('Washed Blue slim jeans W36', 97.85, 'jeans', '{"waist": 36, "inseam": 32, "color": "washed blue", "stretch": false}'::jsonb),
('Floral knee work dress', 97.32, 'dress', '{"size": "XS", "length": "knee", "occasion": "casual", "color": "floral"}'::jsonb),
('Black slim jeans W32', 43.83, 'jeans', '{"waist": 32, "inseam": 30, "color": "black", "stretch": true}'::jsonb),
('M 7-pack socks (red, grey)', 9.6, 'socks', '{"size": "M", "pack_size": 7, "colors": ["red", "grey"]}'::jsonb),
('S 1-pack socks (navy)', 19.57, 'socks', '{"size": "S", "pack_size": 1, "colors": ["navy"]}'::jsonb),
('L 1-pack socks (red)', 14.78, 'socks', '{"size": "L", "pack_size": 1, "colors": ["red"]}'::jsonb),
('M 3-pack socks (brown, navy, white)', 22.22, 'socks', '{"size": "M", "pack_size": 3, "colors": ["brown", "navy", "white"]}'::jsonb),
('S 3-pack socks (white, green, grey)', 21.99, 'socks', '{"size": "S", "pack_size": 3, "colors": ["white", "green", "grey"]}'::jsonb),
('M 1-pack socks (green)', 15.56, 'socks', '{"size": "M", "pack_size": 1, "colors": ["green"]}'::jsonb),
('S 7-pack socks (white, black, navy)', 16.15, 'socks', '{"size": "S", "pack_size": 7, "colors": ["white", "black", "navy"]}'::jsonb),
('M 3-pack socks (navy, red, black)', 14.23, 'socks', '{"size": "M", "pack_size": 3, "colors": ["navy", "red", "black"]}'::jsonb),
('S 7-pack socks (navy, grey)', 9.31, 'socks', '{"size": "S", "pack_size": 7, "colors": ["navy", "grey"]}'::jsonb),
('L 3-pack socks (green, white, red)', 23.49, 'socks', '{"size": "L", "pack_size": 3, "colors": ["green", "white", "red"]}'::jsonb),
('S 3-pack socks (black, brown, green)', 8.41, 'socks', '{"size": "S", "pack_size": 3, "colors": ["black", "brown", "green"]}'::jsonb),
('L 7-pack socks (white, green)', 6.71, 'socks', '{"size": "L", "pack_size": 7, "colors": ["white", "green"]}'::jsonb),
('M 1-pack socks (white)', 11.58, 'socks', '{"size": "M", "pack_size": 1, "colors": ["white"]}'::jsonb),
('L 7-pack socks (brown, black)', 17.8, 'socks', '{"size": "L", "pack_size": 7, "colors": ["brown", "black"]}'::jsonb),
('M 5-pack socks (white, grey, navy, brown)', 23.43, 'socks', '{"size": "M", "pack_size": 5, "colors": ["white", "grey", "navy", "brown"]}'::jsonb);
