-- Exercise 1b: Add computed columns to stg_trips
--
-- Replace (or update) models/staging/stg_trips.sql in your Week 10 dbt project.
--
-- The Materializations chapter builds fct_trips assuming stg_trips already
-- exposes tip_pct, fare_per_mile, and payment_type_label. This exercise adds
-- those three derived columns so fct_trips can use them.
--
-- Start from this template — it has the source reference and basic column list
-- from Chapter 2. Your task is to add the three derived columns.

SELECT
    -- identifiers
    vendorid,
    lpep_pickup_datetime                                AS pickup_datetime,
    lpep_dropoff_datetime                               AS dropoff_datetime,

    -- location keys (used as join keys in fct_trips — keep as integers)
    pulocationid                                        AS pickup_location_id,
    dolocationid                                        AS dropoff_location_id,

    -- trip facts
    trip_distance,
    fare_amount,
    tip_amount,
    payment_type,

    -- TODO 1: add tip_pct using {{ safe_divide('tip_amount', 'fare_amount') }}
    --         alias it as tip_pct

    -- TODO 2: add fare_per_mile using {{ safe_divide('fare_amount', 'trip_distance') }}
    --         alias it as fare_per_mile

    -- TODO 3: add payment_type_label using a {% for %} loop over the TLC code mapping:
    --           1 -> 'Credit card'
    --           2 -> 'Cash'
    --           3 -> 'No charge'
    --           4 -> 'Dispute'
    --           5 -> 'Unknown'
    --           6 -> 'Voided trip'
    --         Use a CASE WHEN block generated by the loop. See the Jinja chapter for
    --         the pattern. The final alias should be payment_type_label.

FROM {{ source('nyc_taxi', 'raw_trips') }}
WHERE pickup_location_id IS NOT NULL
  AND fare_amount >= 0
